config/routes.rb
Rails.application.routes.draw do
  # get 'welcome/index'

  resources :users do
 	resources :followers
  end

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follower.rb
class Follower < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	has_many :followers
	validates :username, presence: true, length:{ minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
	def create
		@user = User.find(params[:user_id])
		@follower = @user.followers.create(follower_params)
			
		redirect_to user_path(@user)
	end

	private
		def follower_params
			params.require(:follower).permit(:name)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)

		if @user.save
			redirect_to @user
		else
			render 'new'
		end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy

		redirect_to users_path
	end

	private
		def user_params
			params.require(:user).permit(:username)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoherentTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
</html>

<body>
	<div class="navbar-default">
    	<div class="container">
	  		<div class="navbar-brand">Twitter Fetch</div>
	  		<%= link_to 'New User', new_user_path, :class=>"navbar-text navbar-right navbar-link"%>
		</div>
  	</div>
  	<div class="container" style="margin-right: 0.5rem;">
	    <%= yield %>
    </div>
</body>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

	<% if @user.errors.any? %>
		<div id="error explanation">
			<h2>
				<%= pluralize(@user.errors.count, "error") %>
				prohibited this user form being fetched
			</h2>
			<ul>
				<% @user.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<p>
		<%= f.text_field :username %>
	</p>

	<p>
		<%= f.submit "Add user", :class=>"btn btn-sm btn-default"%><br>
	</p>

<% end %>

app/views/users/index.html.erb
<div class="usrs">
	<h1>User List</h1>
	<div class="container">
		<table style="margin-left: 2.4rem;">
			

			<% @users.each do |user|%>
					<tr style="padding: 1em 0;">
						<td style="color: rgba(210,210,250, 0.8); padding-top: 1rem; font-size: 1.6rem;"><%= user.username %></td></div>
						<td><%= link_to 'Display', user_path(user), :class=>"btn btn-sm btn-default", :id=>"links", :style=>"margin-left: 2rem; margin-bottom: 1rem;" %></td>
						<td><%= link_to 'Delete', user_path(user), method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-sm btn-default", :id=>"links", :style=>"margin-left: 2rem; margin-bottom: 1rem;" %></td>
					</tr>
			<% end %>

		</table>
	</div>
</div>

app/views/users/new.html.erb
<h1>Input Username</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path, :class=>"btn btn-sm btn-default" %>

app/views/users/show.html.erb
<p>
	<h1>Username</h1>
	<div class="container">
		<h2><%= @user.username %></h2>
	</div>
</p>

<h1>Followers</h1>
<div class="container">
	<div class="box" style="padding-top: 1.6rem;">
		<% TwitterApi.get_followers(@user.username).each do |twitter_name| %>
			<p><%= twitter_name %></p>
		<% end %>
	</div>
</div>

<h1>Saved Followers</h1>
<div class="container">
	<div class="box" style="padding-top: 1.6rem;">
		<% @user.followers.each do |follower| %>
			<p>
				<%= follower.name %>
			</p>
		<% end %>
	</div>
</div>

<%= form_for([@user, @user.followers.build]) do |f| %>
	<p style="color: white; padding: 1.6rem;">
		Insert followers to store:
	</p>
	<p style="color: #333; padding: 1.6rem;">
		<%= f.text_area :name, cols: "25", rows: "7" %>
	</p>
	<p style="padding-left: 1.6rem;">
		<%= f.submit "Store Followers", :class=>"btn btn-sm btn-default"%>
	</p>
<% end %>
	<p style="padding-left: 1.6rem">
		<%= link_to 'Back', users_path, :class=>"btn btn-sm btn-default" %>
	</p>

app/views/welcome/index.html.erb
<!-- <h1>Twitter Fetch</h1> -->
<div class="btn btn-sm btn-default" style="margin-top: 1.6rem;">
	<%= link_to 'Lets Go!', controller: 'users' %>
</div>